<div class="page_content" style="-webkit-transform: translate3d(0px, 0px, 0px);">
    <?php $this->renderPartial('//wechat/common/usertop') ?>
    <div class="col-lg-12" style="padding:10px 25px 0px 25px;min-height:350px;">
        <table class="table table-striped table-hover text-left" style="background-color:#f0f0f0;">
            <tr>
                <th>序号</th>
                <th>标题</th>
                <th>发送人</th>
                <th>操作</th>
            </tr>
            <tr>
                <td>1</td>
                <td>充值100元成功</td>
                <td>系统</td>
                <td>查看</td>
            </tr>
            <tr>
                <td>2</td>
                <td>充值100元成功</td>
                <td>系统</td>
                <td>查看</td>
            </tr>
            <tr>
                <td>3</td>
                <td>充值100元成功</td>
                <td>系统</td>
                <td>查看</td>
            </tr>
            <tr>
                <td>4</td>
                <td>充值100元成功</td>
                <td>系统</td>
                <td>查看</td>
            </tr>
            <tr>
                <td>5</td>
                <td>充值100元成功</td>
                <td>系统</td>
                <td>查看</td>
            </tr>
            <tr>
                <td>7</td>
                <td>充值100元成功</td>
                <td>系统</td>
                <td>查看</td>
            </tr>
            <tr>
                <td>8</td>
                <td>充值100元成功</td>
                <td>系统</td>
                <td>查看</td>
            </tr>
            <tr>
                <td>9</td>
                <td>充值100元成功</td>
                <td>系统</td>
                <td>查看</td>
            </tr>
            <tr>
                <td>10</td>
                <td>充值100元成功</td>
                <td>系统</td>
                <td>查看</td>
            </tr>
            <tr>
                <td>5</td>
                <td>充值100元成功</td>
                <td>系统</td>
                <td>查看</td>
            </tr>
        </table>
    </div>
    <div class="col-lg-12" style="padding:10px 25px 0px 25px;height: 10px;">
    </div>
    <?php $this->renderPartial('//wechat/common/fonterend') ?>
</div>